# Generated by Django 4.1.3 on 2022-12-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_shp_delete_studets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shp',
            new_name='Geoshp',
        ),
    ]
